version: "3.9"
services:
  api:
    build: .
    container_name: "workout-api"
    environment:
      - AZ_TABLE_CONN_STR=${AZ_TABLE_CONN_STR:?err}
      - AZ_TABLE_NAME=${AZ_TABLE_NAME:?err}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - fullstack
    restart: always

networks:
  fullstack:
    driver: bridge