---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workout-api
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      name: workout-api
  template:
    metadata:
      labels:
        name: workout-api
    spec:
      containers:
      - name: application
        image: "thefueley/workout-api:latest"
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        env:
          - name: AZ_TABLE_CONN_STR
            value: "$AZ_TABLE_CONN_STR"
          - name: AZ_TABLE_NAME
            value: "$AZ_TABLE_NAME"